package com.orange.demo

import com.orange.demo.model.User

rule "less than five transactions"
  when
   u: User (transactionCount < 5)
  then
   u.setCommission(10);
end

rule "five to ten transactions and min amount"
  when
   u: User ((transactionCount < 10 && transactionCount > 5), totalTransactionAmount < 500)
  then
   u.setCommission(5);
end


rule "more than ten transactions or min amount"
  when
   u: User (transactionCount > 10 || totalTransactionAmount > 1000)
  then
   u.setCommission(1);
end
